#!/bin/bash
sed 's/template\.json#/template-generated-alternate.json#/g' template.json >template-generated-main.json
sed 's/template\.json#/template-generated-main.json#/g' template.json >template-generated-alternate.json
